<?php
declare(strict_types=1);

namespace Plaisio\CompanyResolver\Test;

use Plaisio\CanonicalHostnameResolver\CanonicalHostnameResolver;
use Plaisio\CompanyResolver\CompanyResolver;
use Plaisio\CompanyResolver\ThirdLevelCompanyResolver;
use Plaisio\Kernel\Nub;

/**
 * Kernel for testing purposes.
 */
class TestKernel extends Nub
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Object constructor.
   */
  public function __construct()
  {
    parent::__construct();
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for deriving the canonical hostname.
   *
   * @return CanonicalHostnameResolver
   */
  protected function getCanonicalHostnameResolver(): CanonicalHostnameResolver
  {
    return new TestCanonicalHostnameResolver();
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for deriving the company.
   *
   * @return CompanyResolver
   */
  protected function getCompanyResolver(): CompanyResolver
  {
    return new ThirdLevelCompanyResolver(T::CMP_ID_SYS);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the data layer generated by PhpStratum.
   *
   * @return TestDataLayer
   */
  protected function getDL(): TestDataLayer
  {
    return new TestDataLayer();
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
