<?php
declare(strict_types=1);

namespace Plaisio\CompanyResolver\Test\Plaisio;

use Plaisio\CanonicalHostnameResolver\CanonicalHostnameResolver;
use Plaisio\CompanyResolver\CompanyResolver;
use Plaisio\CompanyResolver\ThirdLevelCompanyResolver;
use Plaisio\PlaisioKernel;

/**
 * Kernel for testing purposes.
 */
class TestKernel extends PlaisioKernel
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for deriving the canonical hostname.
   *
   * @return CanonicalHostnameResolver
   */
  protected function getCanonicalHostnameResolver(): CanonicalHostnameResolver
  {
    return new TestCanonicalHostnameResolver();
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for deriving the company.
   *
   * @return CompanyResolver
   */
  protected function getCompany(): CompanyResolver
  {
    return new ThirdLevelCompanyResolver($this, T::CMP_ID_SYS);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the data layer generated by PhpStratum.
   *
   * @return TestDataLayer
   */
  protected function getDL(): TestDataLayer
  {
    return new TestDataLayer();
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
